services:
  backend:
    image: oven/bun:latest
    ports:
      - '${DOCKER_PORT}:${PORT}'
    command: bun src/index.ts
    volumes:
      - .:/app
    working_dir: /app
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
